version: '3'
services:
  server:
    tty: true
    stdin_open: true
    container_name: server
    build:
      context: ./server
      dockerfile: dockerfile
    volumes:
      - ./server:/server
    ports:
      - 4000:4000
